[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cc_converter"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.8"

[project.scripts]
cc-convert = "cc_converter.cli:main"
