# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['run_gui.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('cc_converter/template.docx', 'cc_converter'),
        ('cc_converter/templates', 'cc_converter/templates'),
        ('cc_converter/file_handler.html', 'cc_converter'),
    ],
    hiddenimports=[
        'webview',
        'webview.platforms.winforms',
        'webview.platforms.cocoa',
        'cc_converter.gui',
        'cc_converter.hierarchy_converter',
        'cc_converter.docx_converter',
        'cc_converter.xml_parser',
        'cc_converter.models',
        'docx',
        'docx.opc',
        'docx.oxml',
        'docx.shared',
        'docx.enum',
        'watchdog',
        'watchdog.observers',
        'watchdog.events',
        'requests',
        'pathlib',
        'json',
        'threading',
        'logging',
        'datetime',
        'zipfile',
        'html',
        'subprocess',
        'platform',
        'sys',
        'os',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='SchoologyConverter',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
) 