name: Build GUI Application

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -e .
        
    - name: Build Windows executable
      run: |
        pyinstaller SchoologyConverter.spec
        
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: SchoologyConverter-Windows
        path: dist/SchoologyConverter.exe
        
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -e .
        
    - name: Build macOS executable
      run: |
        pyinstaller SchoologyConverter.spec
        
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v3
      with:
        name: SchoologyConverter-macOS
        path: dist/SchoologyConverter
        
  create-release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          SchoologyConverter-Windows/SchoologyConverter.exe
          SchoologyConverter-macOS/SchoologyConverter
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 